name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone identify and fix the bug
        ⚠️ Important!
        After selecting the bug criticality, make sure to add the corresponding GitHub label **at the bottom of this report (e.g., Critical, Serious, Disturbing, Mostly Fun).**
        Without the label, the bug cannot be categorized properly.
        
  - type: input
    id: version
    attributes:
      label: Game Version / Build Number / Branch
      description: |
        In which version of the game or project was the bug observed?
        (For example: build number, game version, editor branch, or commit hash.)
      placeholder: v0.3.1, Build 145, main, commit abc123
    validations:
      required: false
      
  - type: textarea
    id: description
    attributes:
      label: Describe your issue
      placeholder: When I click here this happens
    validations:
      required: true

  - type: checkboxes
    id: criticality
    attributes:
      label: Bug Criticality
      description: |
        How severe is the bug in your opinion?  
        ⚠️ Select one criticality level.          
        **Reminder:** Please add a corresponding label match the criticality level e.g., `Critical`, `Serious`, etc.
      options:
        - label: "4 - Mostly fun / cosmetic — does not affect gameplay or mechanics"
        - label: "3 - Disturbing — affects gameplay noticeably, wrong values, UI mixups"
        - label: "2 - Serious — gets you stuck badly or prevents progress"
        - label: "1 - Critical — crashes the game or breaks core functionality"
    validations:
      required: true

  - type: input
    id: keywords
    attributes:
      label: Keywords
      description: Add keywords to help others find this bug (use short, descriptive tags)
      placeholder: inventory, movement, audio, freeze, quest, save-file

  - type: checkboxes
    id: reproducibility
    attributes:
      label: Reproducibility
      description: |
        How consistently can the bug be reproduced?
        Select the option that best matches your observations.
      options:
        - label: "Always — happens every time"
        - label: "Often — happens in most attempts"
        - label: "Sometimes — happens occasionally"
        - label: "Rarely — hard to reproduce"
        - label: "Unable to reproduce again"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to page X
        2. Click here
        3. Click there
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What was the expected result?
      placeholder: I expected this to happen

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Were you able to bypass or workaround the issue somehow?
      placeholder: |
        Example:
        - Restarting the level helped
        - Switching items avoided the freeze
        - Could not find any workaround

  - type: textarea
    id: screenshots
    attributes:
      label: Put here any screenshots or videos (optional)

  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"

  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! We will get back to you as soon as possible.
