name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone identify and fix the bug

  - type: textarea
    id: description
    attributes:
      label: Describe your issue
      placeholder: When I click here this happens
    validations:
      required: true

  - type: checkboxes
    id: criticality
    attributes:
      label: Bug Criticality
      description: How severe is the bug in your opinion?
      **This is required!** Please select one criticality level.
      Tip: Please add a corresponding keyword to the "Keywords" field below, e.g., `criticality-1`, `criticality-2`, etc.
      options:
        - label: "4 - Mostly fun / cosmetic — does not affect gameplay or mechanics"
        - label: "3 - Disturbing — affects gameplay noticeably, wrong values, UI mixups"
        - label: "2 - Serious — gets you stuck badly or prevents progress"
        - label: "1 - Critical — crashes the game or breaks core functionality"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to page X
        2. Click here
        3. Click there
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What was the expected result?
      placeholder: I expected this to happen

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Were you able to bypass or workaround the issue somehow?
      placeholder: |
        Example:
        - Restarting the level helped
        - Switching items avoided the freeze
        - Could not find any workaround
      render: markdown

  - type: textarea
    id: screenshots
    attributes:
      label: Put here any screenshots or videos (optional)

  - type: input
    id: keywords
    attributes:
      label: Keywords
      description: Add keywords to help others find this bug (use short, descriptive tags)
      placeholder: criticality-x, inventory, movement, audio, freeze, quest, save-file

  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"

  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! We will get back to you as soon as possible.
